#!/bin/tcsh

if ($#argv < 1) then
  printf "  Script to use on-line move mechanisms\n"
  printf "  Usage:\n" 
  printf "        cuikexplore <world file> [dof_1 .... dof_k]\n"
  printf "    where\n" 
  printf "      <world file>   is the mechanism to move.\n"
  printf "      [dof_1..dof_k] the initial dof used as parameters.\n"
else
  geomview -run ./bin/cuikexploration $1 $2 $3 $4 $5 $6 $7 $8 $9 $10 $11 $12 $13 $14 $15 $16 $17 $18 $19 $20
endif
