#!/bin/tcsh
# script to test if all grid nodes are alive
#
echo "Connecting to gmrgrid master"
ssh gmrgrid printf \"   Master is alive and runs \"; echo `uname -a`
echo "Connecting to gmrgrid slaves"
foreach node (1 2 3 4 5 6 7)
  echo "Connecting to gmrgrid$node"
  ssh gmrgrid$node printf \"   Slave is alive and runs \"; echo `uname -a`
end
