#ifndef ERRORTENSEGRITYH
#define ERRORTENSEGRITYH

/** 
   \file error_tensegrity.h

   \brief Error function specific of the tensegrity parser.

   A module that defines an error function used
   in the \b CuikTensegrity library.

   \sa error_tensegrity.c, error.h.
*/

/** 
   \brief Syntax errors in \e .tensegrity files.

   This function is called by the \e .tensegrity file parser 
   when encountering syntax errors.

   \param s A string generated by Bison (Normally it contains "Syntax Error").

   \return EXIT_FAILURE.

   \sa error.h
*/
int ReadTensegrityerror(const char *s); 

#endif
