#ifndef ERRORWORLDH
#define ERRORWORLDH

/** 
   \file error_world.h

   \brief Error function specific of \ref world.c "world".

   A module that defines an error function used
   in the \b CuikWorld library.

   \sa error_world.c, error.h.
*/

/** 
   \brief Syntax errors in \e .world files.

   This function is called by the \e .world file parser 
   when encountering syntax errors.

   \param s A string generated by Bison (Normally it contains "Syntax Error").

   \return EXIT_FAILURE.

   \sa error.h
*/
int ReadWorlderror(const char *s); 

#endif
